### ISSUE TITLE
Texture not displaying properly in cgltf.

### ISSUE THREAD

**Issue by DSPNerd** [floooh/sokol-html5#1]
Texture not displaying (and also holes in mesh).

![Screenshot_2020-06-09-11-01-44](https://user-images.githubusercontent.com/782393/84164665-cb14fa80-aa40-11ea-9d01-f6956394ff06.png)

https://floooh.github.io/sokol-html5/cgltf-sapp.html

Other image/video demos work... Video one stutters... But is awesome.

**Comment by floooh** [comment]
What Android device and browser is this? I basically only tested on iOS devices (I don't have an Android device with a browser that supports WebGL,, so problems on Android are expected unfortunately).

The code which decides what texture format to use is here:

https://github.com/floooh/sokol-samples/blob/d9d97023bd08e4119ddee5a4710da60e0a30e1bf/libs/basisu/basisu_sokol.cpp#L33-L46

It basically starts with the BC formats, if that doesn't work, try PVRTC next (PowerVR texture compression as used on iOS devices), and finally falls back to ETC2 (which sould be supported on most GPUs used in Android devices, but the question is whether the browser supports the compressed extensions too, which unfortunately is much more unlikely).
